### ISSUE TITLE
Clicking Apps sidebar menu item when in app settings

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover-frontend#1]
Not sure whether it's just me, but if I'm on the settings page of a particular app, I would expect that I should be able to get back to Apps 'landing page' just by clicking on the `Apps` sidebar menu item again.  However, it does nothing.  To go back to the landing page I have to scroll back up and find the cross at top-right.  It's OK, not a big deal, but personally I think it would be better to have quick access to the Apps landing page again just by clicking on the sidebar.  In other words, clicking on the Apps sidebar menu item should have the same effect (go to Apps landing page) no matter where you are in the UI.

**Comment by githubsaturn** [comment]
Yup - it's already addressed in https://github.com/caprover/caprover-frontend/pull/2

Will be fixed in the next release.
