### ISSUE TITLE
Group Apps / App Collection

### ISSUE THREAD

**Issue by joseph-Eliphas** [caprover/caprover-frontend#134]
Ability to create a collection of apps from your app list
eg: MyApp has a frontend, backend and multiple micro-services and i want to easily access them without having to scroll through the whole app list.

--MyApp
----myapp-console
----myapp-backend
----myapp-website
----e.t.c

**Comment by githubsaturn** [comment]
You can already group your apps using tags. Clicking on any tag will filter the entire list to the apps with that tag

<img width="600" alt="image" src="https://github.com/caprover/caprover-frontend/assets/10582082/8f3b7c60-3182-4d79-9959-3a7083787275">
