### ISSUE TITLE
[Request] Collapsing containers with the same name

### ISSUE THREAD

**Issue by EgloDevelopment** [caprover/caprover-frontend#143]
Hello, I currently have about ~10 containers for this one service, and it's really cluttering up the container list, I was wondering if there would be a way to implement a dropdown-like system for containers starting with the same name, such as if there are 3 containers that start with "my-app" (Eg. my-app-mongo, my-app-frontend, my-app-backend), they would be clustered together automatically and hid inside a dropdown, so that their collapsed space only takes up 1 row instead of 3. So far the only problem I have had with CapRover, really great system and I am loving it.

**Comment by githubsaturn** [comment]
Projects are now supported in CapRover. You can group your apps under one project!
