### ISSUE TITLE
Redesign of Caprover Frontend!

### ISSUE THREAD

**Issue by dhruvilxcode** [caprover/caprover-frontend#147]
Hi Community!
I'm Dhruvil Patel, Product Designer & Full Stack Developer.

i'm interested in doing redesign of the Caprover Frontend to make it more vibrant, with good UI.
The current UI works perfect, i've made revamp of my favourite Open Source Repo Caprover, and here we go.

Your suggestions are welcome! I designed it in Figma, and more screens are under design, so in this thread i will share more updates.

Figma Prototype Link:
[View Prototype](https://www.figma.com/proto/oZh1aUlSzg73GHV2xKygJZ/Caprover-Redesign?page-id=0%3A1&type=design&node-id=2-2&viewport=559%2C409%2C0.6&t=h82HpJpgfb7NmGeb-1&scaling=scale-down&starting-point-node-id=2%3A2&mode=design)

### Login Screen
![Screenshot 2024-04-30 at 10 40 39 AM](https://github.com/caprover/caprover-frontend/assets/60258514/71f575e7-e296-45f9-bfcb-eb4d82222bae)

### Dashboard Screen
![Screenshot 2024-04-30 at 10 40 53 AM](https://github.com/caprover/caprover-frontend/assets/60258514/63b8f819-48b9-43d8-9b0f-3ed6fe6a1043)

### Create new app
![Screenshot 2024-04-30 at 10 41 04 AM](https://github.com/caprover/caprover-frontend/assets/60258514/7e350c67-e338-4e95-9501-f2a071340293)

### Apps
![Screenshot 2024-04-30 at 10 41 18 AM](https://github.com/caprover/caprover-frontend/assets/60258514/9a575244-ca7e-4010-80e9-1cda1ca18f17)

**Comment by githubsaturn** [comment]
This looks great! Thanks, @dhruvilxcode !

Looking forward to see the full set!

**Comment by dhruvilxcode** [comment]
@githubsaturn Kasra Bigdeli 
Thanks for your kind words!

**Comment by dhruvilxcode** [comment]
### App Detail Screen - HTTP Settings
<img width="1230" alt="Screenshot 2024-05-03 at 10 37 12 PM" src="https://github.com/caprover/caprover-frontend/assets/60258514/7f324cf8-618a-43d9-b43c-8e8f5cad9ae7">

**Comment by githubsaturn** [comment]
For the implementation, let's break this into two parts:
Step 1: just theme update. Feel free to submit a PR with the theme update
Step 2: iterative updates for the UX. This one requires more work and alignment to make sure UX is set up right (grouping the options etc etc)

**Comment by dhruvilxcode** [comment]
👍

**Comment by thegrtnx** [comment]
> For the implementation, let's break this into two parts: Step 1: just theme update. I've asked the community to comment, once we got a good signal about this, feel free to submit a PR with the theme update. Step 2: iterative updates for the UX. This one requires more work and alignment to make sure UX is set up right (grouping the options etc etc)

I'll be glad to help on frontend web development for this.

**Comment by dhruvilxcode** [comment]
We can divide the Revamp of Caprover in smaller tasks, and can maintain it as Beta. 

So atleast we can start the work. 

What do you think about this @githubsaturn 

We can make GitHub Project Board.

**Comment by itxtoledo** [comment]
@githubsaturn I think there are more important things to do ahead than a complete redesign of the interface, which already works well today. We need things like:

projects: ability to create projects and within a project create our apps.

ssh inside caprover: ability to access the terminal where an app is running within the caprover interface itself.

multiple accounts with different access levels.

Among many other things that other PaaS have, such as Coolify.

**Comment by githubsaturn** [comment]
@itxtoledo - it's not either or. For each feature request, feel free to open an issue on github, if it gets enough upvotes, it'll be top priority when working on new features. Projects and SSH into container from the web console aren't in the issues AFAIK. Feel free to upvote, or create a new issue if it doesn't exist.

These are the top requested features as of now: 
https://github.com/caprover/caprover/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by githubsaturn** [comment]
CapRover now has support for custom themes! Please feel to submit your custom themes!
