### ISSUE TITLE
Using the frontend API programmatically with OTP enabled?

### ISSUE THREAD

**Issue by ms4sman** [caprover/caprover-frontend#154]
Is it possible to programmatically use the frontend API when I have OTP enabled on my login?

I see that if I just provide a password like I used to, it will respond and tell me I need the OTP as well, which makes sense. But this is for a project that runs in the background as a job, so it needs to authenticate on its own without me intervening to give it an OTP. 

Is there a way around this? Or is it simply not possible with OTP turned on?

Thanks!

**Comment by githubsaturn** [comment]
You can certainly obtain OTP as a parameter to the login screen:
```bash
curl 'https://captain.domain.com/api/v2/login' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'content-type: application/json' \
  -H 'x-namespace: captain' \
  --data-raw '{"password":"MyPassword","otpToken":"123456"}'
  ```

Also there a lot of tools that can generate OTP tokens programmatically - here is one: https://otplib.yeojz.dev/
