### ISSUE TITLE
is there a way to move `A template for creating one- click apps` to the top?

### ISSUE THREAD

**Issue by wajeht** [caprover/caprover-frontend#156]
<img width="311" alt="image" src="https://github.com/user-attachments/assets/f4ba2ac4-37f5-427e-a50c-20d02d1b6139">

Is there a way to move `A template for creating one-click apps` to the top? I have to scroll all the way down every time I need to make changes to iterate on creating the one-click app template.

**Comment by githubsaturn** [comment]
Just type for `>>` and it'll popup!

![image](https://github.com/user-attachments/assets/c24b8e52-bc40-4ae7-b58d-8fdf6c14dc7f)
