### ISSUE TITLE
European date format

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover-frontend#157]
Currently the date is displayed in US date format mmddyy:

![image](https://github.com/user-attachments/assets/29a3bdf7-5608-4348-a20c-1585ba8308db)

Would be great if there was an option to display it in European date format ddmmyy.

**Comment by thgh** [comment]
It seems to be using the browser locale 
<img width="146" alt="Screenshot 2024-09-23 at 11 16 18" src="https://github.com/user-attachments/assets/df9f2c34-eaf7-4455-84f5-0d073ffccdfa">

**Comment by drmrbrewer** [comment]
@thgh on my [languages setup page](chrome://settings/languages) in Chrome I see:

![image](https://github.com/user-attachments/assets/aa6fb6bd-1e64-4b9c-ac0c-a038fae08038)

So based on this, it should be showing non-US date format?  I can't see any other locale setting to change.  I tried overriding the location in DevTools ([see here](https://stackoverflow.com/a/69149258/4070848)) to Berlin and London, but regardless of location it's still showing US date format in CapRover.

**Comment by githubsaturn** [comment]
@thgh you're not on the latest version. This is a regression introduced as I was trying to make the column shorter.

**Comment by drmrbrewer** [comment]
@githubsaturn I just updated to the latest CapRover and it seems that there is no change to the date format... these are today's date (6 Nov 2024):

![image](https://github.com/user-attachments/assets/47edd4f5-bcb1-4632-9b48-787b4a0f4a09)

Same for Last Deployed dates on App page:

![image](https://github.com/user-attachments/assets/e46e0b48-2389-49f6-a315-2df2525cbf28)

My browser languages settings are unchanged (see above).

**Comment by githubsaturn** [comment]
See here: https://github.com/caprover/caprover/issues/2185

**Comment by drmrbrewer** [comment]
OK.  Not sure where moment is getting the idea that the date should be in US format, because both browser and system all seem to be set to European/UK date format... I don't see the US format anywhere apart from in CapRover:

system:

![image](https://github.com/user-attachments/assets/15236077-b211-4f84-accb-4bc4af9e4a26)

browser:

![image](https://github.com/user-attachments/assets/35674021-a15d-4063-af3b-3066f4bb1f5c)

CapRover:

![image](https://github.com/user-attachments/assets/6c058468-b8e3-4a7a-9f9a-c4588451cda4)

Anyway, hopefully the new fix will do it!

**Comment by githubsaturn** [comment]
Yea that's weird. Anyways the new fix used built-in Date so it should work 🤞

**Comment by drmrbrewer** [comment]
Yep, I confirm that it's fixed in `1.13.2`, thanks!
