### ISSUE TITLE
Modifying app list page UX

### ISSUE THREAD

**Issue by DiamondYuan** [caprover/caprover-frontend#170]
Why modify.

1. Creating apps is relatively infrequent, and currently one occupies the upper area, which is rather obtrusive.
2. Currently the height of the app list at the bottom changes, causing the page to bounce.

My suggestion

1. let the app list occupy the whole page, no change in height.
2. put create app into the drawer.

![CleanShot 2024-11-09 at 16 24 36@2x](https://github.com/user-attachments/assets/a7b11de6-9190-48c4-954d-9bace3dde176)

![CleanShot 2024-11-09 at 16 18 27@2x](https://github.com/user-attachments/assets/f30b2dd5-5e2d-4294-84e2-9aa92cfdb613)

**Comment by githubsaturn** [comment]
Hi @DiamondYuan ! 

Left some comments on your Slack message, but for the sake of completeness:


There is a [similar PR](https://github.com/caprover/caprover-frontend/pull/163) a few weeks back but they didn't get to finish it. 

The right drawer is not the best solution for new app UI. Drawers are generally used for rare edits, extra information etc. What I recommend is go with the approach that is in the PR and simply hide and show the current "create app" UI.
