### ISSUE TITLE
PWA HTML5 manifest is default and buggy

### ISSUE THREAD

**Issue by mxdpeep** [caprover/caprover-frontend#23]
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

> If you are having problems with deploying a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?
`  "short_name": "React App",`

should be: "CapRover"

` "name": "Create React App Sample",`

should be: "CapRover PaaS console"

` "src": "favicon.ico",`

do not use ICO files, use PNG icons
check this example: https://gscloud.cz/manifest.json?lang=cs

**Comment by githubsaturn** [comment]
Fixed in https://github.com/caprover/caprover-frontend/pull/24
