### ISSUE TITLE
Convert one-click apps dropdown from a select to a grid

### ISSUE THREAD

**Issue by vohzd** [caprover/caprover-frontend#30]
After reading the below GH issue, thought it could be an idea to change the dropdown to be a grid layout, kind of like the Digitalocean marketplace (where I see Caprover is there too!). Could even be expanded to include appName, appDesc, and if it ever comes to it, appImage.

https://github.com/caprover/one-click-apps/issues/96

I'm happy to work on this and submit a PR if this is a worthwhile addition.

**Comment by githubsaturn** [comment]
This sounds good. Let's break it down:

- one click json changes:
Let's add a displayData field in the json with name, description, logoName.

- create a logo directory to keep logos. No need to reformat the logos to png or JPG. We can use logoName field appropriately. 

- modify a few one click app definitions and add the new display fields

- proposal for front end: grid view with search functionality.

**Comment by EmrysMyrddin** [comment]
Are you sure we should have the logo in the repo ?

**Comment by githubsaturn** [comment]
Yea, at first I thought about just having a URL, but then i realized that it could break at anytime. Having logos on the repo ensures consistent behavior.

**Comment by EmrysMyrddin** [comment]
Makes sense. I just hope licences allow us to store this images in our repo :-)

**Comment by EmrysMyrddin** [comment]
We should store logos in the one click app repo then ?

**Comment by githubsaturn** [comment]
> Makes sense. I just hope licences allow us to store this images in our repo :-)

That's a valid concern. But I believe as long as the logo is used to refer to the intended product, it's fine. 


And yes, we'll keep the logos in one click app repo.

**Comment by githubsaturn** [comment]
This is implemented and will be released in 1.6.0
