### ISSUE TITLE
Tab items not clear on a mobile device

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover-frontend#35]
Just a minor UI improvement suggestion, on a mobile device with limited screen space.

On browsing to the page of an app, you see the following content:

![Screenshot_20191122-075604](https://user-images.githubusercontent.com/9009792/69432198-21368080-0d31-11ea-9210-46bd7815afea.jpg)

Note that the tab only displays one item (HTTP Settings), plus a vary small slither of the second one.   OK so you then click on the right arrow to pan across, but then you still only see part of the second item (now the second part of it)... difficult to read and also difficult to ensure you tap in the right place if that's the item you want to select:

![Screenshot_20191122-075628](https://user-images.githubusercontent.com/9009792/69432158-1380fb00-0d31-11ea-84b0-413d4893fccc.jpg)

Would be better if some other UI element was available on a small screen, e.g. a drop-down or similar, rather than tabs... or at least make it so that moving across the tab items does so in a way that allows you to see the whole item text.

**Comment by githubsaturn** [comment]
Fixed here: https://github.com/caprover/caprover-frontend/pull/61
