### ISSUE TITLE
Unresponsive UI after closing settings for app

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover-frontend#4]
This seems to be happening fairly consistently.  If I go to the settings of an app of mine that outputs quite a lot of logging, and click on the Deployment tab to see the logs, it usually takes a little time for anything at all to appear in the logs panel (and when it does there is an issue reported [here](https://github.com/caprover/caprover/issues/366)).

But then when I click the cross at the top right, to try and go back to the app listing page, I get the circling "waiting" symbol which appears to last indefinitely.  In fact, after I waited around four minutes, the waiting symbol did go, and the app listing page did appear.  But within that four minutes or so, the entire UI is unresponsive like this... whatever page or tab you click on you get the waiting symbol only.

In [this comment](https://github.com/caprover/caprover/issues/366#issuecomment-462225951) you suggest that it may relate to the new "reduced downtime" feature in CapRover, but in this case I do nothing on the app's page before closing it with the cross... in particular I do not Update and Save.  I do not re-deploy the app or update it in any way.  I just view the logs page and then close the app's settings.

I think this only tends to happen for this one app that has a more hefty log output... doesn't seem to for other apps with only a light log output.  May be related to that somehow?

**Comment by githubsaturn** [comment]
> in particular I do not Update and Save. I do not re-deploy the app or update it in any way. I just view the logs page and then close the app's settings.

Okay, then it's not what I thought it might be.


> I think this only tends to happen for this one app that has a more hefty log output... doesn't seem to for other apps with only a light log output. May be related to that somehow?

When you say hefty output, do you mean it generates a lot of logs continuously? Or it already has a lot of logs? e.g., an app that generates 200 logs a second vs an app that has been running for a week and it generates 10 lines per second.

Can you create a repro case for it? Also, let me know if you're running it on a cluster and if it's being replicated with more than 1 running instance.

**Comment by drmrbrewer** [comment]
What I mean is that the app concerned generates a log entry maybe three times a second on average, continuously.  But I've tried (without success) to reproduce this behaviour with [this test](https://github.com/drmrbrewer/captest), which I've modified just to make it run longer and also log which node it's on.  The "real" app is on a cluster with more than 1 running instance, but even when I run the above test on the same cluster and scaled to 3 instances, I can't get the same hanging behaviour in the CapRover console, even when I've let it run for a while to generate lots of log entries.  But maybe it's significant that with this test app I do *not* see the error messages noted in [this issue](https://github.com/caprover/caprover/issues/366), and maybe that's significant?

Sorry, not much help.

**Comment by drmrbrewer** [comment]
Just some more observations...  

With the "problem" app, when I browse to the Deployment tab to see the logs, it takes a long time for anything to appear in the logs panel (around 40 seconds)... then I get some logs but also the error messages.  This doesn't happen with the test app... logs appear quite soon.

Then when I click on the cross to close the app's page and go back to the app listing, it waits a loooong time (minutes) in an unresponsive state, but does eventually get back to the app listing page.

And **after** returning to the app listing, the captain logs (`docker service logs captain-captain --since 1m --timestamps --raw`) show:

	2019-02-12T09:10:56.160840094Z GET /checkhealth 200 0.408 ms - 36
	2019-02-12T09:11:05.757681361Z GET /api/v2/user/apps/appData/myapp/logs - - ms - -
	2019-02-12T09:11:05.884032065Z GET /api/v2/user/apps/appData/myapp 200 0.697 ms - 301
	2019-02-12T09:11:06.002827295Z GET /api/v2/user/apps/appData/myapp 200 7.298 ms - 301
	2019-02-12T09:11:17.172426302Z GET /checkhealth 302 1.072 ms - 75
	2019-02-12T09:11:17.177358837Z GET /checkhealth 200 0.414 ms - 36
	2019-02-12T09:11:29.693219128Z GET /api/v2/user/apps/appData/myapp/logs - - ms - -
	2019-02-12T09:11:29.806717381Z GET /api/v2/user/apps/appData/myapp 200 0.980 ms - 301
	2019-02-12T09:11:35.100984136Z GET /api/v2/user/apps/appData/myapp/logs - - ms - -
	2019-02-12T09:11:35.212249010Z GET /api/v2/user/apps/appData/myapp 200 0.619 ms - 301
	2019-02-12T09:11:35.318465472Z GET /api/v2/user/apps/appData/myapp 200 0.764 ms - 301
	2019-02-12T09:11:38.209068859Z GET /checkhealth 302 0.171 ms - 75
	2019-02-12T09:11:38.214373712Z GET /checkhealth 200 0.607 ms - 36
	2019-02-12T09:11:42.574964071Z GET /api/v2/user/apps/appData/myapp/logs - - ms - -
	2019-02-12T09:11:42.726878666Z GET /api/v2/user/apps/appData/myapp 200 1.394 ms - 301
	2019-02-12T09:11:42.878818151Z GET /api/v2/user/apps/appData/myapp 200 0.743 ms - 301

It looks as it there are still requests to get the logs for myapp?  And several of them?  Maybe captain is still trying to get logs after closing the Deployment tab, and trying several times, each time taking ~40 seconds?  The log entries above suggest that the logs fetch is not successful (no response code)?  And there also appear to be requests to get info of some sort (`GET /api/v2/user/apps/appData/myapp`) despite me having already closed the page for `myapp`.

**Comment by githubsaturn** [comment]
What you're referring to in the second comment is jamming the request pipeline and that's I think what causing the really long loading time for other requests. I did find out about this yesterday and fixed it (not released yet). With the new fix, CapRover waits for the previous log request to come back before it issues a new one. Previously it used to issue one every 3sec or so.

Having said that, the underlying issue is the service.getLogs() call from Docker API that hangs. I yet have to find a solid reproducible case and forward to Docker people.

**Comment by githubsaturn** [comment]
> Having said that, the underlying issue is the service.getLogs() call from Docker API that hangs. I yet have to find a solid reproducible case and forward to Docker people.

Confirmed. This is a Docker bug. I was able to reproduce it by running this: `docker service logs srv-captain--test-logging --tail 500` a few times (~10 times in a row in my case)

Docker hangs and does nothing! Just give it a ctrl+c, and do again, everything is normal.

**Comment by githubsaturn** [comment]
And... Of course, it's been reported: https://github.com/moby/moby/issues/38640


Closing this issue as this is confirmed to be a Docker bug.

**Comment by drmrbrewer** [comment]
There seem to be lots of open issues for Docker!

Until it is fixed, it would be good to have a way of disabling logs in CapRover (so that the UI doesn't hang every time I view this page)?  I know you can hide the panel, but (a) this doesn't persist (next time you go there, it's open again); and (b) I'm not sure whether hiding the panel actually stops the logs information from being requested, so the problem might remain?

I also wonder whether having logs information under the Deployment tab is the best place?  I wouldn't naturally look in Deployment if I was trying to find logs.  The logs are relevant even three months *after* deployment.

**Comment by githubsaturn** [comment]
With the new fix, even if docker hangs, the UI stays functional. 

As for the placement of logs, deployment is the best for now. But once we have more features for monitoring of an individual app, we'll create a separate tab for it.
