### ISSUE TITLE
Webhook URL is not generated

### ISSUE THREAD

**Issue by s-kris** [caprover/caprover-frontend#41]
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

> If you are having problems with deploying a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?

Webhook URL is not generated after adding a new app and setting up CD (repo/branch/username/password) github repo. I noticed this after recent update to caprover. I'm running three instances of caprover on three different servers (2 digital ocean, 1 aws-lightsail) and all of them have the same issue. I tried to deploy multiple apps like api-server, static gatsby-site etc. 

If applicable, content of `captain-definition` file:

Steps to reproduce the problem:
1. Update to latest version of caprover 
2. Add a new app
3. Setup deploy from github
4. Webhook URL is not generated

Answers to the following questions where applicable:
Three instances of caprover
- Your OS and version? Ubuntu 18.04
- RAM? 16GB, 4GB, 1 GB

**Comment by drmrbrewer** [comment]
+1 on this... came here to report this problem too.

**Comment by koolamusic** [comment]
Same here

**Comment by githubsaturn** [comment]
Fixed in 1.7
