### ISSUE TITLE
Minor formatting issues

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover-frontend#43]
On the Monitoring tab, missing spaces here:

![image](https://user-images.githubusercontent.com/9009792/80302757-e33bfd80-87a3-11ea-83c1-47dedc3a9a74.png)

![image](https://user-images.githubusercontent.com/9009792/80302735-ca334c80-87a3-11ea-871e-34d252e24171.png)

And superfluous space here:

![image](https://user-images.githubusercontent.com/9009792/80302778-0b2b6100-87a4-11ea-8a84-3490b720d666.png)

I tried to edit and create a pull request but I don't understand the tsx format enough to know what I'm doing... and why the spaces are not appearing in the final html.

**Comment by githubsaturn** [comment]
Thanks!
