### ISSUE TITLE
Allow to choose, or default to a different start tab

### ISSUE THREAD

**Issue by JosXa** [caprover/caprover-frontend#48]
Every time I log into my caprover instance I am greeted with something like "Hello and welcome, your Caprover is **now** fully set up and ready" while usually what I want to do is see my deployed apps. 
It would be nice to set that as the default tab or allow the user to choose the default location on login.

**Comment by drmrbrewer** [comment]
+1 on this.  I don't need to see this same information every time I log on to CapRover.  In fact, it seems to me that the Dashboard page could be removed entirely because it doesn't really provide any useful function?  The Change Root Domain function could be moved into Settings?

**Comment by githubsaturn** [comment]
Done in https://github.com/caprover/caprover-frontend/commit/1c22bfb36c25e43583549119990ec68cf150cb9e


Will be released as 1.8
