### ISSUE TITLE
Fix Link on custom one click app Page (tiny bug)

### ISSUE THREAD

**Issue by divrse** [caprover/caprover-frontend#53]
Filepath: src/containers/apps/oneclick/selector/OneClickAppSelector.tsx
Line Number: 82
Issue: pointing to v2 github
Fix: Change ``` <NewTabLink url="https://github.com/caprover/one-click-apps/tree/master/public/v2/apps">```
to udpated link:
```   <NewTabLink url="https://github.com/caprover/one-click-apps/tree/master/public/v4/apps">```

Id fix this myself and submit  PR but kinda lazy

**Comment by githubsaturn** [comment]
Thanks!
