### ISSUE TITLE
[Bug] Cannot read property 'timeStamp' of undefined

### ISSUE THREAD

**Issue by alexkainzinger** [caprover/caprover-frontend#56]
Hey there, 

I recently discovered a very nasty bug where basically the whole UI bricks.
It usually occurs when I deploy an application and create a new one a couple of seconds later.

Basically bricks whole UI at forces me to login again, to see the same blank page again with the same error message. Once the application has been deployed, the UI works again.

![image](https://user-images.githubusercontent.com/10105613/96584313-556a4680-12de-11eb-8fa0-76a7be70f23d.png)

**Comment by githubsaturn** [comment]
Thanks for reporting this.
Do you have a reproducible step-by-step case for this?

**Comment by alexkainzinger** [comment]
Thanks for the quick reply!

CapRover Version: 1.8.0

1. "Create New App" in "Apps"
2.  Configure deployment "Method 3" (Github in my case)
3. Stay in "Deployment" tab and trigger build-process
4. Building/Deployment process has to be running
5. Press on "Apps" in sidebar + create new app with any name
6. UI bricks + refreshing the dashboard forces new login
(7.) after login error can still occurs until the build process has finished

Seems like the API does return a malformed response while there is a building/deployment process running which causes the UI to brick.

Thanks!

**Comment by githubsaturn** [comment]
I don't seem to be able to reproduce it on my end. I added some more logs. Can you please [upgrade to the edge version](https://caprover.com/docs/troubleshooting.html#how-to-use-the-edge-version) and try to see if you can get the extra logs. Note that the error is now "fixed" and your UI will not break anymore, but [some logs will be outputted to the console](https://github.com/caprover/caprover-frontend/commit/b9d394a0c8f5923f5535624ce13bfb84da265130).

**Comment by alexkainzinger** [comment]
Yes that fixes the UI, thank you!

Error log:
![image](https://user-images.githubusercontent.com/10105613/96842247-1575a180-144d-11eb-9ee8-1d53f730ade2.png)

**Comment by maxerbox** [comment]
There is still an issue with app versions, if the array is empty I get a "app.version.filter" is not a function. I deleted manually the app

**Comment by githubsaturn** [comment]
ah! You're 100% correct! Thanks for the ping! The frontend repo hash wasn't updated during the release :facepalm: 

I'll cut a new release soon.
