### ISSUE TITLE
[Bug] if I click on Show Password, it gets cached in the UI, and all registries show this same password

### ISSUE THREAD

**Issue by simplytech** [caprover/caprover-frontend#69]
I added 2 remote registries:

- registry.gitlab.com
- registry-1.docker.io

Both have proper User, Password, Domain (otherwise, if you use dummy values when creating a registry, the authentication fails. However, I am able to edit a registry to put dummy passwords, and it seems to accept it so I will open a different bug for this)

When I change the password in registry.gitlab.com  (by clicking on the Edit action, then Save and Update), the password looks like it gets changed in registry-1.docker.io as well, but that’s not what is really happening: I think the Show Password is remembering the last displayed password, and displays it in the current registry. To reproduce:

1. Click the Edit action on registry.gitlab.com, Show Password, change it to gitlab123, Save and Update.
2. Click the Edit action on registry-1.docker.io, Show Password, change it to docker456, Save and Update.
3. Click the Edit action on registry-1.docker.io, Show Password, I see docker456, Cancel
4. Click the Edit action on registry.gitlab.com, the Show Password is not there. Instead, I see docker456 (I expect to see Show Password, and when I click it, I expect to see gitlab123)
5. Click Apps, Click Cluster.
6. Click the Edit action on registry.gitlab.com, the Show Password is now back.  when I click it, I see gitlab123, Cancel
7. Click the Edit action on registry-1.docker.io, the Show Password is not there. Instead, I see gitlab123 (I expect to see Show Password, and when I click it, I expect to see docker456)

**Comment by githubsaturn** [comment]
Thanks for the report, fixed in https://github.com/caprover/caprover-frontend/commit/e0385e25d2533e0eb862f81287fb09dadbabf213
