### ISSUE TITLE
Logs panel suggestions: resize and stop tailing

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover-frontend#7]
Would be nice if the App Logs panel was resizable vertically, like the one for Pre-Deploy Script for example.  Sometimes the narrow-ish window on the logs is quite restrictive when trying to scan the logs by eye.  

Would also be nice if there was an option to stop tailing the logs (freeze it in current position).  E.g. with heroku logs there is a 'tail' checkbox which automatically unchecks itself when you scroll up from the bottom (and checks itself again when you scroll back to the bottom).

Both "nice to haves" rather than "vitals" :)

**Comment by githubsaturn** [comment]
> Would also be nice if there was an option to stop tailing the logs (freeze it in current position). E.g. with heroku logs there is a 'tail' checkbox which automatically unchecks itself when you scroll up from the bottom (and checks itself again when you scroll back to the bottom).

This should not be an issue. The tailing is "smart", it deactivates itself once you scroll up. It's only tailing if you're scrolled to the bottom (with a 100px slop)
