### ISSUE TITLE
Can I redesign your frontend?

### ISSUE THREAD

**Issue by junaid33** [caprover/caprover-frontend#9]
Hey, I really love Caprover and was wondering if I could contribute by redesigning the frontend using [evergreen-ui](https://github.com/segmentio/evergreen) instead of Ant Design. I think it will look a lot cleaner and I can do a pull request if you like the design. What do you think?

**Comment by githubsaturn** [comment]
Hi, thanks for your interest. But there is no point in redesigning the frontend. It's working perfectly fine now, and also ant design is a good design system that's being actively maintained.

Having said that, keep it mind that this project is open source, so feel free to play with it and create your own version of the frontend if you'd like to.
