### ISSUE TITLE
[Suggestion] Automatic disk cleanup

### ISSUE THREAD

**Issue by Thibstars** [caprover/caprover-frontend#95]
On the settings page, there is a 'Disk Cleanup' feature, which would be nice to have automised. I work on pretty small virtual machines, so I would like to perform the disk cleanup after every new deploy (any app). This way I will no longer forget to perform this task and it will always cleanup some unused RAM.

I suggest to make this an opt-in feature.

**Comment by githubsaturn** [comment]
Closing old issues.
Already implemented: https://github.com/caprover/caprover/blob/master/CHANGELOG.md#1120---2024-08-17
